// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNmwgBxDZh2EYkVzJN75OrQCKXrBiNfo0',
    appId: '1:2829596289:web:060ab860832d9429cb3f80',
    messagingSenderId: '2829596289',
    projectId: 'toplearn-shop',
    authDomain: 'toplearn-shop.firebaseapp.com',
    storageBucket: 'toplearn-shop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfIaGGgu7p8qOJASUmZ1X1Bqbmd-W0KhY',
    appId: '1:2829596289:android:8fed4d05fe3e12f6cb3f80',
    messagingSenderId: '2829596289',
    projectId: 'toplearn-shop',
    storageBucket: 'toplearn-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTeHPMoV1eq3LXIHyWX1n4_i5I-oaz8GE',
    appId: '1:2829596289:ios:2a54ca38027877b6cb3f80',
    messagingSenderId: '2829596289',
    projectId: 'toplearn-shop',
    storageBucket: 'toplearn-shop.appspot.com',
    iosClientId:
        '2829596289-4a6s82fu65a5vb7bl4mbo2atsl9rsbql.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );
}
